# General
title: DMV Scapes
description: Softscaping and hardscaping
#baseurl: ""
url: https://dmvscapes.com
phone: 571-462-3495
email: dmvscapes@gmail.com 

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
# Collections
collections:
  pages:
    output: true
    permalink: :title
